import { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, X, CheckCircle, XCircle, AlertTriangle, Loader2 } from 'lucide-react';
import type { ScanResult } from '../../context/LabelGuardContext';
import { fetchReportText, renderReportText } from '../../utils/scanPdfReport';

interface PDFReportModalProps {
  result: ScanResult;
  onClose: () => void;
}

export const PDFReportModal = ({ result, onClose }: PDFReportModalProps) => {
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const generateReport = async () => {
    setGenerating(true);
    await new Promise(resolve => setTimeout(resolve, 2000));
    setGenerating(false);
    setGenerated(true);
  };

  const downloadReport = async () => {
    try {
      setDownloading(true);
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ unit: 'pt', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 48;
      let y = 56;

    const teal: [number, number, number] = [20, 184, 166];

    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 4, 'F');
    doc.setFillColor(20, 184, 166);
    doc.rect(0, 4, pageWidth, 3, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(...teal);
    doc.text('LabelGuard AI - Compliance Report', margin, y);
    y += 22;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(85, 90, 100);
    doc.text(`Generated: ${new Date(result.timestamp).toLocaleString()}   |   Scan ID: ${result.id}`, margin, y);
    y += 30;

    // Let the local LLM write the report; fall back to a local build if offline.
    const reportText = await fetchReportText(result);
    y = renderReportText(doc, reportText, { pageWidth, margin, startY: y });

    // Disclaimer
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    y += 10;
    doc.text('DISCLAIMER: AI-Assisted Assessment', margin, y);
    y += 16;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(90, 70, 10);
    doc.text(
      'This report is generated by an AI-assisted compliance screening tool for educational purposes only. ' +
      'The final legal determination rests with an authorized officer under the Legal Metrology Act, 2009. ' +
      'This assessment does not constitute legal advice.',
      margin, y, { maxWidth: pageWidth - 2 * margin }
    );

    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LabelGuard-Report-${result.id.slice(0, 8)}.pdf`;
    a.click();
    URL.revokeObjectURL(url);
    setDownloading(false);
    } catch (err) {
      setDownloading(false);
      console.error('PDF download failed:', err);
      alert('Failed to generate the PDF report. Please try again, or check that the backend is running.');
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'PASS': return <CheckCircle className="w-4 h-4 text-emerald-400" />;
      case 'FAIL': return <XCircle className="w-4 h-4 text-red-400" />;
      default: return <AlertTriangle className="w-4 h-4 text-amber-400" />;
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto bg-[#0a0a0a] rounded-3xl border border-white/10"
        onClick={e => e.stopPropagation()}
      >
        <div className="sticky top-0 bg-[#0a0a0a] p-6 border-b border-white/10 flex justify-between items-start">
          <div>
            <h2 className="text-2xl font-bold text-white">Compliance Report</h2>
            <p className="text-gray-400 text-sm mt-1">Generated on {new Date(result.timestamp).toLocaleString()}</p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center text-gray-400 hover:text-white hover:bg-white/10 transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        <div className="p-6 space-y-6">
          {/* Summary Card */}
          <div className="p-6 rounded-2xl bg-gradient-to-br from-teal-500/10 to-cyan-500/5 border border-teal-500/20">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="text-xl font-bold text-white">{result.product.product_name || 'Unknown Product'}</h3>
                <p className="text-gray-400">{result.product.manufacturer || 'Unknown Manufacturer'}</p>
              </div>
              <div className="text-right">
                <div className="text-4xl font-bold text-white">{result.compliance.score}</div>
                <div className="text-sm text-gray-400">Compliance Score</div>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                result.compliance.risk_level === 'LOW' ? 'bg-emerald-500/20 text-emerald-400' :
                result.compliance.risk_level === 'MEDIUM' ? 'bg-amber-500/20 text-amber-400' :
                'bg-red-500/20 text-red-400'
              }`}>
                {result.compliance.risk_level} Risk
              </span>
              <span className="text-gray-400 text-sm">
                {result.compliance.checks.filter(c => c.status === 'PASS').length}/{result.compliance.checks.length} checks passed
              </span>
            </div>
          </div>

          {/* Product Details */}
          <div>
            <h3 className="text-lg font-semibold text-white mb-4">Product Details</h3>
            <div className="grid grid-cols-2 gap-3">
              {Object.entries(result.product).map(([key, value]) => (
                value && (
                  <div key={key} className="p-3 rounded-xl bg-white/[0.02] border border-white/5">
                    <div className="text-xs text-gray-500 uppercase mb-1">{key.replace(/_/g, ' ')}</div>
                    <div className="text-white text-sm truncate">{value}</div>
                  </div>
                )
              ))}
            </div>
          </div>

          {/* Compliance Checks */}
          <div>
            <h3 className="text-lg font-semibold text-white mb-4">Compliance Checks</h3>
            <div className="space-y-2">
              {result.compliance.checks.map((check) => (
                <div
                  key={check.field}
                  className={`p-4 rounded-xl border ${
                    check.status === 'PASS' ? 'bg-emerald-500/5 border-emerald-500/20' :
                    check.status === 'FAIL' ? 'bg-red-500/5 border-red-500/20' :
                    'bg-amber-500/5 border-amber-500/20'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      {getStatusIcon(check.status)}
                      <div>
                        <div className="text-white font-medium">{check.field.replace(/_/g, ' ')}</div>
                        <div className="text-gray-400 text-xs">{check.law || check.rule_citation}</div>
                      </div>
                    </div>
                    <div className="text-right">
                      <div className={`text-sm font-medium ${
                        check.status === 'PASS' ? 'text-emerald-400' :
                        check.status === 'FAIL' ? 'text-red-400' :
                        'text-amber-400'
                      }`}>
                        {check.status}
                      </div>
                      <div className="text-gray-500 text-xs">{(check.confidence * 100).toFixed(0)}% confidence</div>
                    </div>
                  </div>
                  {check.value && (
                    <div className="mt-2 text-gray-400 text-sm truncate">{check.value}</div>
                  )}
                  {check.reason && (
                    <div className={`mt-2 text-sm ${
                      check.status === 'PASS' ? 'text-emerald-300/90' :
                      check.status === 'FAIL' ? 'text-red-300/90' :
                      'text-amber-300/90'
                    }`}>
                      {check.reason}
                    </div>
                  )}
                  {check.requirement && (
                    <div className="mt-1 text-xs text-gray-500">
                      <span className="text-gray-600 uppercase tracking-wide">Requirement:</span> {check.requirement}
                    </div>
                  )}
                  {check.status === 'FAIL' && check.violation && (
                    <div className="mt-2 p-2 rounded-lg bg-red-500/10 border border-red-500/20">
                      <div className="text-xs text-red-200 leading-relaxed">
                        <span className="font-semibold text-red-300 uppercase tracking-wide">⚠ Non-Compliant: </span>
                        {check.violation}
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Disclaimer */}
          <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
              <div>
                <h4 className="text-amber-400 font-medium mb-1">AI-Assisted Assessment Disclaimer</h4>
                <p className="text-amber-400/80 text-sm">
                  This report is generated by an AI-assisted compliance screening tool for educational purposes. 
                  The final legal determination rests with an authorized officer under the Legal Metrology Act, 2009.
                  This assessment does not constitute legal advice.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="sticky bottom-0 bg-[#0a0a0a] p-6 border-t border-white/10">
          <div className="flex gap-3">
            {!generated ? (
              <button
                onClick={generateReport}
                disabled={generating}
                className="flex-1 flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-teal-500 to-cyan-500 text-white font-medium disabled:opacity-50 hover:from-teal-400 hover:to-cyan-400 transition-all"
              >
                {generating ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <FileText className="w-5 h-5" />
                    Generate PDF Report
                  </>
                )}
              </button>
            ) : (
              <button
                onClick={downloadReport}
                disabled={downloading}
                className="flex-1 flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-teal-500 to-cyan-500 text-white font-medium hover:from-teal-400 hover:to-cyan-400 transition-all disabled:opacity-50"
              >
                {downloading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Preparing PDF...
                  </>
                ) : (
                  <>
                    <Download className="w-5 h-5" />
                    Download PDF
                  </>
                )}
              </button>
            )}
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
};
